### ISSUE TITLE
Doesn't work anymore

### ISSUE THREAD

**Issue by SheepCommander** [SammCheese/Alternative-Blocking#2]
![image](https://user-images.githubusercontent.com/66646514/148684063-c5ba58fe-162d-4ce0-855b-0466e1452b41.png)
![image](https://user-images.githubusercontent.com/66646514/148684074-3ea2603d-02ec-448b-82a4-ec18f12d1eba.png)

**Comment by SammCheese** [comment]
Fixed

**Comment by SheepCommander** [comment]
Yep it works, thanks
